source "https://rubygems.org"
ruby '2.5.1'
gem 'dotenv'
gem 'nokogiri'
gem 'gmail'
gem 'json'
gem 'pp'
gem 'csv'
gem 'google_drive'
gem 'twitter'
gem 'rubocop', '~> 0.57.2'
gem 'pry'
gem 'rake', '< 11.0'
gem 'rspec', '~> 3.4'
